// src/pages/Terms.tsx
import React from 'react';

const Terms: React.FC = () => {
  return (
    <div className="pt-20 p-8 max-w-4xl mx-auto text-gray-800">
      <h1 className="text-3xl font-bold mb-6"></h1>
      <p className="mb-4">

Terms & Conditions
Updated at 2025-05-31

General Terms
By accessing and placing an order with GLOW HERB, you confirm that you are in agreement with and bound by the terms of service contained in the Terms & Conditions outlined below. These terms apply to the entire website and any email or other type of communication between you and GLOW HERB. Under no circumstances shall GLOW HERB team be liable for any direct, indirect, special, incidental, or consequential damages, including, but not limited to, loss of data or profit, arising out of the use, or the inability to use, the materials on this site, even if GLOW HERB team or an authorized representative has been advised of the possibility of such damages. If your use of materials from this site results in the need for servicing, repair, or correction of equipment or data, you assume any costs thereof. GLOW HERB will not be responsible for any outcome that may occur during the course of usage of our resources. We reserve the right to change prices and revise the resources usage policy at any moment without any prior intimation / notice.

License
GLOW HERB grants you a revocable, non-exclusive, non-transferable, limited license to download, install and use the website strictly in accordance with the terms of this Agreement. These Terms & Conditions are a contract between you and GLOW HERB (referred to in these Terms & Conditions as "GLOW HERB", "us", "we" or "our"), the provider of the GLOW HERB website and the services accessible from the GLOW HERB website (which are collectively referred to in these Terms & Conditions as the "GLOW HERB Service"). You are agreeing to be bound by these Terms & Conditions. If you do not agree to these Terms & Conditions, please do not use the GLOW HERB Service. In these Terms & Conditions, "you" refers both to you as an individual and to the entity you represent. If you violate any of these Terms & Conditions, we reserve the right to cancel your account or block access to your account without notice.

Definitions and key terms
To help explain things as clearly as possible in this Terms & Conditions, every time any of these terms are referenced, are strictly defined as:

Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.

Company: when these terms mention “Company,” “we,” “us,” or “our,” it refers to GLOW HERB, that is responsible for your information under this Terms & Conditions.

Country: where GLOW HERB or the owners/founders of GLOW HERB are based, in this case is India.

Device: any internet-connected device such as a phone, tablet, computer, or any other device that can be used to visit GLOW HERB and use the services.

Service: refers to the service provided by GLOW HERB as described in the relative terms (if available) and on this platform.

Third-party service: refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.



You: a person or entity that is registered with GLOW HERB to use the Services.


Contact Us
Don't hesitate to contact us if you have any questions. 
Via Email: glowherbnaturalshomemadeproduc@gmail.com 
Via Phone Number: 7708434624

Return & Refund Policy
Updated at 2025-05-31

We do not allow returns or refunds for any purchases made through our website. All sales are final and non-refundable. If the order is damaged or wrong product sent then we will process you with a refund.
</p>
    </div>
  );
};

export default Terms;
